import os.path

DIAS_TOTALES_TORNEO = 15
ARENA_INICIAL = 'normal'
CANTIDAD_EXCAVADORES_INICIALES = 3
METROS_META = 150
PROB_ENCONTRAR_TESORO = 0.22
PROB_ENCONTRAR_CONSUMIBLE = 0.78
PROB_INICIAR_EVENTO = 0.41
PROB_LLUVIA = 0.39
PROB_TERREMOTO = 0.44
PROB_DERRUMBE = 0.17
METROS_PERDIDOS_DERRUMBE = 50
FELICIDAD_PERDIDA = 2
POND_ARENA_NORMAL = 0.420
PROB_ENCONTRAR_ITEM = 0.62
FELICIDAD_ADICIONAL_DOCENCIO = 4
FUERZA_ADICIONAL_DOCENCIO = 3
ENERGIA_PERDIDA_DOCENCIO = 11
ENERGIA_ADICIONAL_TAREO = 23
SUERTE_ADICIONAL_TAREO = 4
EDAD_ADICIONAL_TAREO = 5
FELICIDAD_PERDIDA_TAREO = 3

PATH_CONSUMIBLES = os.path.join('Datos', 'consumibles.csv')
PATH_TESOROS = os.path.join('Datos', 'tesoros.csv')
PATH_ARENAS = os.path.join('Datos', 'arenas.csv')
PATH_EXCAVADORES = os.path.join('Datos', 'excavadores.csv')
PATH_PARTIDAS = os.path.join('Partidas')
